version: '3.9'
services:

  uptime-kuma:
    container_name: main-dashboard
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /compose_data/uptime-kuma-data:/app/data
    ports: 
      - "127.0.0.1:3001:3001"  # <Host Port>:<Container Port>
    restart: always

  adminer:
    container_name: db-panel
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:4001:8080"
 
  mysql_db:
    container_name: mysql-db
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "3306"
 
  postgres_db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"

  sql_db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
      ACCEPT_EULA: "Y"
    secrets:
      - db_password
  
  mongo_bd:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "27017:27017"

  redis_db:
    container_name: redis-db
    image: redis
    restart: always

secrets:
  db_password:
    file: db_password.txt
