version: '3.9'
services:

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /compose_data/uptime-kuma-data:/app/data
    ports: 
      - 127.0.0.1:3001:3001  # <Host Port>:<Container Port>
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:4001:8080
